[tool.poetry]
name = "hw-8"
version = "0.1.0"
description = ""
authors = ["taras <taras5500@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
faker = "^18.10.1"
pymongo = "^4.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"